# Adopt version 2 syntax
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local
services:
    nginx:
        container_name: my-project-nginx
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    php:
        container_name: my-project-php
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
              
    mariadb:
        container_name: my-project-mariadb
        image: mariadb:latest
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql
            - .:/home/root/localfiles
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_project_db
            MYSQL_USER: my_project_db
            MYSQL_PASSWORD: my_project_db
